import type { Metadata } from "next";
import "./globals.css";
import Header from "@/app/components/header/header.app";
import Navbar from "@/app/components/navbar/navbar.menu";
import Footer from "@/app/components/footer/footer.app";
import { Toaster } from "react-hot-toast";
import NextAuthWrapper from "@/app/lib/next.auth.wrapper";
import { sendRequest } from "./util/api";
import SessionErrorHandler from "./lib/session.error";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const res = await sendRequest<IBackendRes<IModelPaginateRestJPA<IBrand>>>({
    url: `${process.env.NEXT_PUBLIC_BACKEND_URL}/api/v1/brands`,
    method: 'GET'
  });

  const brands = res.data?._embedded.brands || [] as IBrand[];
  return (
    <html lang="en">
      <body>
        <NextAuthWrapper>
          <SessionErrorHandler>
            <Header brands={brands} />
            <Navbar brands={brands} />
            {children}
            <Footer />
            <Toaster position="top-right" reverseOrder={false} />
          </SessionErrorHandler>
        </NextAuthWrapper>
      </body>
    </html>
  );
}
