import type { Metadata } from "next";
import "./globals.css";
import Header from "@/app/components/header/header.app";
import Navbar from "@/app/components/navbar/navbar.menu";
import Footer from "@/app/components/footer/footer.app";
import { Toaster } from "react-hot-toast";
import NextAuthWrapper from "@/app/lib/next.auth.wrapper";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NextAuthWrapper>
          <Header />
          <Navbar />
          {children}
          <Footer />
          <Toaster position="top-center" reverseOrder={false} />
        </NextAuthWrapper>
      </body>
    </html>
  );
}
